import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import localFont from "next/font/local";
import SmoothScrolling from "@/components/ui/smoothScrolling";

// const inter = Inter({ subsets: ['latin'] });
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const myFont = localFont({
  src: [
    {
      path: "../public/fonts/OverusedGrotesk-Roman.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/OverusedGrotesk-Italic.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "../public/fonts/OverusedGrotesk-BoldItalic.woff2",
      weight: "700",
      style: "italic",
    },
    {
      path: "../public/fonts/OverusedGrotesk-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/OverusedGrotesk-Black.woff2",
      weight: "900",
      style: "normal",
    },
    {
      path: "../public/fonts/OverusedGrotesk-BlackItalic.woff2",
      weight: "900",
      style: "italic",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={`${inter.className} ${myFont.className}`}>
          <SmoothScrolling>
            <Toaster />
            {children}
          </SmoothScrolling>
        </body>
      </html>
    </SessionProvider>
  );
}
